Added Slack Guidelines
Vizzuality/playbook pull request #64
Opened 2021-02-01 10:55 UTC by gretacv

```
This PR adds slack-guidelines.md which contains Information on how to use Slack (linked to the Slack documentation), some recommendations and usage guidelines to: (1) help on transparency, organisation of information, (2) reduce noise and lack of focus, which lead to more efficiency and better well being

Anyone can review this PR.

As per our Playbook, one of our default group decision making tools is “Consent” and we will be using this tool on this occasion. “Consent” ensures that no one “strongly opposes” (objects) a course of action, while allowing progress to move forward. 

When reading the proposal please reflect on the following:

Do you have any reason(s) why adopting this proposal would cause harm or move us backwards as a team?
Is this good enough for now, safe enough to try?

Timeline: 5 Working Days. By close of play Tuesday next week (8th February, 5pm EST) 

The document includes the following: 
```

The aim of the slack guidelines is to: (1) help on transparency, organisation of information, (2) reduce noise and lack of focus, which lead to more efficiency and better well being.

Slack is expected to be an asynchronous form of communication. It is not aimed at documenting decisions and storing important documents.

-   Synchronous communication: communication that happens in real-time, with instant reads and responses.
    
-   Asynchronous communication: communication that does not happen in real-time, where responses are intermittent.
    

  

## Customise Notification and View settings

Get familiar with the Slack preferences and options to customise notifications and the view, this can be helpful to reduce the noise and increase the focus.

Below are helpful links to best practices and tips on managing your notifications and reducing noise in Slack.

-   [Reduce noise in Slack](https://slack.com/intl/en-gb/help/articles/218551977-Reduce-noise-in-Slack)
    
-   [Configure Your Notifications](https://slack.com/intl/en-gb/help/articles/201355156-Guide-to-desktop-notifications#configure-your-notifications)
    
-   [Guide to Desktop Notifications](https://slack.com/intl/en-gb/help/articles/201355156-Guide-to-desktop-notifications#channel-specific-and-group-dm-notifications)
    
-   [Channel-specific and group DM Notifications](https://slack.com/intl/en-gb/help/articles/201355156-Guide-to-desktop-notifications#channel-specific-and-group-dm-notifications)
    
-   [Display only unread conversations](https://slack.com/help/articles/360043207674-Organize-your-sidebar-with-custom-sections-Organize-your-sidebar-with-custom-sections-Organize-your-sidebar-with-custom-sections#manage-conversation-display)
    
-   [Mute channels](https://slack.com/help/articles/204411433-Mute-channels-and-direct-messages)
    

Consider using Slack's [Sections](https://slack.com/intl/en-es/help/articles/360043207674-Organize-your-sidebar-with-custom-sections) to categorise channels and set up their visibility on the side bar.

### Recommended customisation

-   **Look & Feel**: As you explore the preferences of Slack, you might want to change the theme to use the Vizzuality colours for the sidebar. `#000000,#222222,#000000,#FFE229,#222222,#FFFFFF,#2BA4A0,#2BA4A0,#222222,#FFFFFF`
    

-   **Sections**: You can organise your channels in Slack using [sections](https://slack.com/intl/en-es/help/articles/360043207674-Organize-your-sidebar-with-custom-sections).  
    This is very personal and depending on how you want to organise your slack you choose how categorise the channels. Some ways are categorising by project, functional area, topic, or how frequently you have to check them...
    
-   **Channel presence**: leaving a channel is not a problem, come and go as you like.  
    NOTE: See below usage guidelines, we assume that people on a channel are interested in the topic, and anybody who does not actively participate consents to what is being said.  
    That’s why is important to post everything publicly and on the right channels and tag people or groups when necessary,
    
-   The [status and availability in Slack](https://slack.com/intl/en-es/help/articles/201864558-Set-your-Slack-status-and-availability)  can help inform everyone on how quickly you might be able to respond. You can use a custom status and duration, but we have some predefined ones in our workspace:  
    - `In a meeting`: (lasts an hour) It synchronises with your Google Calendar, or you can put it manually.  
    - `Nom nom nom break`: (lasts an hour) break time for lunch.  
    - `BRB!`: (permanent) to notify when you are away from the computer or busy.  
    - `Vacationing`: Use this status to notify of your absence because of vacations.  
    - `Working remotely`: To notify you are working from a remote location.
    

  

# Usage guidelines

While the customisation of slack is a personal choice, the usage guidelines explain what is expected from each individual when creating channels and sending messages.

## Conflict resolution

Slack is a place to discuss topics, and in Vizzuality we embrace conflict in a positive way. In Slack we follow the same rules of communication we follow on the rest of channels in Vizzuality, you a have a couple of link to know more about this:

-   [Conflict resolution guidelines.](https://vizzuality.github.io/playbook/conflict-resolution/)
    
-   Blogin Post about SMO: [Embracing conflicts](https://vizzuality.blogin.co/posts/98949).
    
-   Using [non-violent communication](https://docs.google.com/document/d/1pDFKsCQOezYqXbdphi4kXRK_rpmAyPMGSFeSIvKFD0k/edit?usp=sharing).
    

## Channel Life Cycle

Anyone can create a channel. There is a list of current channels in [this doc](https://docs.google.com/spreadsheets/d/18FrEu9G8pH7LSe13YnwxfZusUDzsbuzk5wFOT7La4Xc/edit#gid=0), it is updated monthly.

### Guidelines to add a new channel:

1.  Use the search bar in slack to see if there is a channel with the topic of interest, you can also check the channel [list](https://docs.google.com/spreadsheets/d/18FrEu9G8pH7LSe13YnwxfZusUDzsbuzk5wFOT7La4Xc/edit#gid=0) to see if there is already a channel for your purpose.
    
2.  Set a channel name that states the purpose of the channel, use the naming nomenclature. Be highly descriptive in the name. Where appropriate use the full project or Functional Area names especially where acronyms are not well known (e.g. `#half-earth-whatever`, not `#he-whatever`).
    

    1.  use hyphens/dashes separators
    
    2.  Name should include one or several of the following:
    

        -   `<project name>` and/or
    
        -   `<functional area>`
    
        -   `<theme>` e.g. quality, SMO, comms, etc
    
        -   `<task>` e.g. retro, workshop, proposal, QA/QC etc
    
        -   `<time>` e.g. year and/or quarter
    
        -   `<shared status>` i.e. include 'shared' if shared with another org
    
        -   `legal-<people-affected>-<theme>` (more information below)
    

4.  Add a description to the channel:
    

    -  Purpose: why this channel exist and who is expected to be in the channel
    
    -  Related channels
    
    -  Channel handle (optional, see more about channel handles below)
    

6.  Invite all relevant parties
    
7.  Monitor the usage of the channel. When you create a channel you are responsible for achieving it when its use is no longer necessary.
    

### Closing guidelines:

1.  Inform the channel of the planned closure
    
2.  Channel must be archived after used
    

  

## Channels vs Direct messages

### Note: We don't use the term private message, because these direct messages are not inherently private like a phone call or private letter. The messages are potentially accessible by Workspace admins or via Backups. Slack refers to these types of messages as [direct messages themselves](https://slack.com/intl/en-de/help/articles/212281468-What-is-a-direct-message).

### Public channels

Public Slack channels are used for digital communication. This saves time in filling [...]

2021-02-01 11:23 UTC, 01painadam requested changes

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +-   Asynchronous communication: communication that does not happen in real-time, where responses are intermittent.
`where responses are **delayed**`

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +    That’s why is important to post everything publicly and on the right channels and tag people or groups when necessary,
This isn't related to customisation - move this to guidelines.

Also: `we assume that people on a channel are interested in the topic` I would add `we assume that people on a channel are interested in the topic **right now**`

There are channels I'm interested in (long term) but not right now/actively. Again, makes it even more concrete how okay it is to come and go as you need. Just because youre not there now doesn't mean you can' return (or be _summoned_ for that matter)

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +    1.  use hyphens/dashes separators
remove plural: `hyphen/dash separators`

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +-   `@channel` or `@here` should be avoided unless really necessary - meaning everyone in that channel should be **immediately** aware of something.
Include link to the difference and etiquette of here/everyone/channel

https://slack.com/intl/en-es/help/articles/202009646-Notify-a-channel-or-workspace#:~:text=%40everyone%20notifies%20every%20person%20in,active%20members%20of%20a%20channel.&text=If%20there%20are%2010%2C000%20members,use%20%40channel%20or%20%40here.

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +-   Discussions should be kept within threads and the outcome of the conversation shared as well in the channel. The `:thread:` emoji is used to remind of this guideline.
I would add the reasoning. Discussion threads make the page history easily navigable and reduces the noise in any given channel of a simple index of topics. 

Also worth adding about following/unfollowing threads here (as its alluded to below)

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +When using group private messages keep in mind that they are very hard to maintain, track and respond to. You might want to consider whether the conversation can take place in a public channel.
It may also warrant the creation of a new channel.

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +From the side bar you can see which [user groups](https://slack.com/intl/en-es/help/articles/212906697-Create-a-user-group) already exist (People and user groups). Some channels have specified user g
(under `People and user groups` - this may be hidden inside the `More ...` tab)

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +-   **User groups of a project**: These are useful handles for daily stand ups or important project notifications. Depending on the development status of the project different people will be part of
Should project handles be visible in the channel description?

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +-   `#Project-name-channel`: Debriefing from client meetings, broadcasting outcomes from meetings, discussions on the wide scope of the project live here.
use variables `#<project name>-channel` to make it obvious its an example - i was confused for a sec that we had a channel called `#project-name-channel` 😅

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +-   `#Project-name-dev`: The different team members should ask for information to other members in this channel, the day to day teamwork happens here.
Same here: `#<project name>-dev`

2021-02-01 11:23 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +-   Thematic: `books`, `#gamez`, `#music`, `#pets`, `#run`
`#books`

2021-02-01 13:02 UTC, pablopareja commented on guidelines/slack-guidelines.md
> +-   `#Project-name-dev`: The different team members should ask for information to other members in this channel, the day to day teamwork happens here.
I thought that the `#<project name>-dev` channel was intended for technical things exclusively, i.e. conversations between the FE/BE developers _(perhaps Data/Science sometimes as well)_ that go too much into detail to be of interest to other roles involved in a project, such as e.g. design, user research, or pm. In my experience from the projects I've been working on during the past few years we've always used the `#<project-name>-channel` for discussions where potentially any role could/should be involved.

2021-02-01 13:10 UTC, tiagojsag commented on guidelines/slack-guidelines.md
> +-   Discussions should be kept within threads and the outcome of the conversation shared as well in the channel. The `:thread:` emoji is used to remind of this guideline.
you mentioned above that slack "<...> is not aimed at documenting decisions and storing important documents" so maybe encourage people to document important decisions elsewhere.

2021-02-01 13:10 UTC, tiagojsag commented on guidelines/slack-guidelines.md
> +When using private messages be aware that private messages discourage collaboration. You might actually be contacting the wrong person, and they cannot easily redirect you to the right person. If the
private -> direct

2021-02-01 14:03 UTC, craigmmills commented
Perhaps we could include a retrospective element to this (and possible all) guidelines? For this one, can we measure the two objectives of "(1) help on transparency, organisation of information, (2) reduce noise and lack of focus, which lead to more efficiency and better well being."

1. Can we see the speed it takes to find out something?
2. Perhaps there is a small poll (e.g. How distracting do you find slack? 0- what's slack? to 10 - can you make this a slack poll in #random otherwise I won't see it) - we could run before the start of this guidelines and after 6 weeks?

2021-02-01 14:31 UTC, 01painadam commented
> 1. Can we see the speed it takes to find out something?

If _something_ is any arbitrary piece of information I absolutely put myself forward to run this expt 😄  You could see how many degrees of freedom there are on the walk to getting an answer to a question. How many _"ask so-and-so"'s_ do you get along that path?

> 2. Perhaps there is a small poll (e.g. How distracting do you find slack? 0- what's slack? to 10 - can you make this a slack poll in #random otherwise I won't see it) - we could run before the start of this guidelines and after 6 weeks?

There was one (in one-team I think) ahead of this. Problem is... we need to ask the question many times (how do we know its significant? Maybe slack _was_ super busy that week).

2021-02-01 17:19 UTC, gretacv commented on guidelines/slack-guidelines.md
> +-   **User groups of a project**: These are useful handles for daily stand ups or important project notifications. Depending on the development status of the project different people will be part of
Yes, above in the creation of a channel it is indicated. I will remind it in this section.

2021-02-01 17:25 UTC, gretacv commented
> Perhaps we could include a retrospective element to this (and possible all) guidelines? For this one, can we measure the two objectives of "(1) help on transparency, organisation of information, (2) reduce noise and lack of focus, which lead to more efficiency and better well being."
> 
> 1. Can we see the speed it takes to find out something?
> 2. Perhaps there is a small poll (e.g. How distracting do you find slack? 0- what's slack? to 10 - can you make this a slack poll in #random otherwise I won't see it) - we could run before the start of this guidelines and after 6 weeks?

I think that is a great idea, but I don't know if that suggestion is for this PR. I think it makes more sense as an amendment of the the readme file. I am happy to monitor how the guideline is doing in a few months, but I am not sure that information should be included in the guideline itself.

2021-02-01 17:44 UTC, gretacv commented on guidelines/slack-guidelines.md
> +-   `#Project-name-dev`: The different team members should ask for information to other members in this channel, the day to day teamwork happens here.
@pablopareja, I will summon @pablourrutia as this comes from the PM's guidelines. From my point of view the important thing is to have a clear description of the channel stating who is expected to be there.

2021-02-01 18:41 UTC, d4weed commented on guidelines/slack-guidelines.md
> +    That’s why is important to post everything publicly and on the right channels and tag people or groups when necessary,
I agree, plus I wouldn't use the word "consents" as that is reserved for decision making, a consent process can not be based on a slack conversation, it should happen (like this very one" in a place where it can be reviewed asynchronously, like github or blogin

2021-02-01 18:43 UTC, d4weed commented on guidelines/slack-guidelines.md
> +    That’s why is important to post everything publicly and on the right channels and tag people or groups when necessary,
(plus there needs to be a well-defined timeline for it)

2021-02-02 07:54 UTC, luisasteixeira commented on guidelines/slack-guidelines.md
> +2.  Set a channel name that states the purpose of the channel, use the naming nomenclature. Be highly descriptive in the name. Where appropriate use the full project or Functional Area names especial
Is this update automatic or does it involve any human action? If it is the latter, it would be great to make it clear and to integrate it in the guidelines, if we see this doc as essential for the Slack upkeep process.

2021-02-02 07:59 UTC, 01painadam commented on guidelines/slack-guidelines.md
> +2.  Set a channel name that states the purpose of the channel, use the naming nomenclature. Be highly descriptive in the name. Where appropriate use the full project or Functional Area names especial
I made a script - needs, a little tweaking but its will be mostly automated. I just need your admin key :D

2021-02-02 08:03 UTC, luisasteixeira commented on guidelines/slack-guidelines.md
> +
It seems that Operational channels aren't the channel for Operations work? I am unsure about suggesting to include #invoices, but #vizz-tracker could fit here as well?

fyi the # is missing in capacity-planning

2021-02-02 08:11 UTC, pablourrutia commented on guidelines/slack-guidelines.md
> +-   `#Project-name-dev`: The different team members should ask for information to other members in this channel, the day to day teamwork happens here.
@pablopareja and @gretacv what Pablo says sounds good to me. I am not aware of how this channel should be used and if it says #<project name>-dev, by these guidelines (and logic) makes sense that is for developers and people interested in those decisions.

2021-02-02 16:09 UTC, d4weed commented
> Note: We don't use the term private message, because these direct messages are not inherently private like a phone call or private letter. The messages are potentially accessible by Workspace admins or via Backups

@gretacv this paragraph is incorrect and potentially misleading. Under our plan (Standard) admins can't read or export any DMs or private channels.

The only way workspace owners in standard plans can export private messages is under limited circumstances. They must first provide a valid legal process, consent of the members (employees) and a requirement or right under applicable laws.

I'd suggest removing this as we don't want our team to think someone may be reading their DMs

2021-02-04 17:06 UTC, gretacv commented on guidelines/slack-guidelines.md
> +
I missed out on Vizz tracker! thanks for the heads up. My thinking about invoices is that it is a very PM specific channel... My thinking about these "operational" channels is that they directly affect all the FAs.

2021-02-04 17:08 UTC, gretacv commented
> > Note: We don't use the term private message, because these direct messages are not inherently private like a phone call or private letter. The messages are potentially accessible by Workspace admins or via Backups
> 
> @gretacv this paragraph is incorrect and potentially misleading. Under our plan (Standard) admins can't read or export any DMs or private channels.
> 
> The only way workspace owners in standard plans can export private messages is under limited circumstances. They must first provide a valid legal process, consent of the members (employees) and a requirement or right under applicable laws.
> 
> I'd suggest removing this as we don't want our team to think someone may be reading their DMs

Removed, thanks for clarifying. It was definitely wrong ☺️ I think however it is ok to use the wording of "direct message" over "private message".

2021-02-04 17:13 UTC, gretacv commented on guidelines/slack-guidelines.md
> +    That’s why is important to post everything publicly and on the right channels and tag people or groups when necessary,
I am going to summon @pablourrutia to rephrase this part because I am unsure of the thinking behind it.

2021-02-04 17:15 UTC, gretacv commented on guidelines/slack-guidelines.md
> +-   `#Project-name-dev`: The different team members should ask for information to other members in this channel, the day to day teamwork happens here.
I am rewording the description in that there is a focus on the development phase. 
> -   `#<Project name>-dev`: The different team members should ask for information to other members in this channel during the development of the channel.
(please, comment after commit ☺️ )

2021-02-04 17:18 UTC, gretacv commented on guidelines/slack-guidelines.md
> +2.  Set a channel name that states the purpose of the channel, use the naming nomenclature. Be highly descriptive in the name. Where appropriate use the full project or Functional Area names especial
"manual trigger" added to the reviewing.

2021-02-05 12:11 UTC, gretacv commented on guidelines/slack-guidelines.md
> +    That’s why is important to post everything publicly and on the right channels and tag people or groups when necessary,
I have made a commit rewording. I have removed references to consent.

2021-02-10 08:41 UTC, 01painadam approved these changes
Happy with the changes - no objection to merging!

2021-02-10 08:55 UTC, merged